console.log("utuy")
console.log("karthi")
console.log("rubesh")
console.log("madara")
console.log("Dragon Ball")
console.log("Jackie Chan")
console.log("Action Kamen")
console.log("Quantom Robot")
console.log("aswini")
console.log("gopal")